### PR TITLE
feat: invite link

### PR DESCRIPTION
**Pull request by peterpeterparker**
### Feature Description

This PR adds the support for invite link, as discussed in issues #843 and [#1074](https://github.com/ChildMindInstitute/mindlogger-backend/issues/1074), to the web application.

### Backend

The related backend PR which adds the new endpoints is [#1075](https://github.com/ChildMindInstitute/mindlogger-backend/pull/1075).

### Admin

The related admin PR to create invite link is [#1061](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1061).

### Credits

This pull request is part of the "Citizen Science Logger" project and, provided by the [ETH Library Lab](https://www.librarylab.ethz.ch/).

### CODE REVIEW

**Comment by WorldImpex** [comment]
@peterpeterparker Could you fix the conflicts?

**Comment by peterpeterparker** [comment]
@WorldImpex when is it plan to merge this PR?

If you aim to merge it soonish, sure happy to resolve the conflict right now but, if you plan to merge it in several times/couple of weeks, rather wait until that point as I guess I would have to resolve other conflicts later on.

**Comment by jj105** [comment]
@peterpeterparker I reviewed the PR. ( cc @WorldImpex )
I tested accept button and confirmed that it's working fine.

I have two suggestions.
1 - If click "accept invitation" button in invitation page, it shows me "Invitation Accepted" text in existing page rather than new page.
image

I think we can show invitation accepted message in new page or we can show activity list page.

2 - if user is already joined to applet and he clicks invitation link, then we are showing up this page to user.
could we do same for public invitation link?

image

**Comment by peterpeterparker** [comment]
@jj105 thanks for the feedback

1. there is no "new page" even in the actual case of an invitation. When a study is accepted, user remains on the same page and only the text "Invitation accepted" is displayed (current behavior in production).

Therefore, to match you request, I modified this PR accordingly. When an open invite link is accepted, then the text "Invitation accepted" will be displayed and only this text. The invite link details are now going to be hidden.

2. I guess this would be possible if the user details are interpreted when a public invite link is fetched. The backend would need to get the details of the user, get the invite link and cross check both to test if user already joined this study or not.

That being said, we are not going to provide such feature.

Our pull requests do amend the fact that a user cannot join multiple times de same study and, we decide on purpose to not add this complexity.

ps.: @WorldImpex I have resolve the conflicts. Note that there was some because the code is malformed on `web-prod` respectively because you do not apply `prettier`.

Screenshots:

"Normal" invitation, no navigation, same page:

Capture d’écran 2021-06-25 à 07 28 45

Update in this PR, only "Invitation accepted" text displayed:

Capture d’écran 2021-06-25 à 07 32 18

**Pull request merged**
